apiVersion: batch/v1
kind: Job
metadata:
  name: job-sleep
spec:
  completions: 21
  parallelism: 21
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: pi
        image: bash
        command: ["bash",  "-c", "echo will sleep;sleep 15;echo done"]
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: '0'
      restartPolicy: Never
  backoffLimit: 4
