apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apple-sts
  labels:
    app: apple-sts
spec:
  serviceName: apple-service
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apple-sts
  template:
    metadata:
      labels:
        app: apple-sts
    spec:
      containers:
        - name: apple-sts
          image: nginxdemos/hello:plain-text
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-sts
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: apple-sts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-sts
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /apple-sts
            pathType: Prefix
            backend:
              service:
                name: app-service-sts
                port:
                  number: 8080